Formatting

diff --git a/pnu/etc/redis/prod/redis-pnu-user-server b/pnu/etc/redis/prod/redis-pnu-user-server
--- a/pnu/etc/redis/prod/redis-pnu-user-server
+++ b/pnu/etc/redis/prod/redis-pnu-user-server
@@ -26,7 +26,7 @@ test -x $DAEMON || exit 0
 
 if [ -r /etc/default/$NAME ]
 then
-	. /etc/default/$NAME
+  . /etc/default/$NAME
 fi
 
 . /lib/lsb/init-functions
@@ -35,56 +35,56 @@ set -e
 
 case "$1" in
   start)
-	echo -n "Starting $DESC: "
-	mkdir -p $RUNDIR
-	touch $PIDFILE
-	chown redis:redis $RUNDIR $PIDFILE
-	chmod 755 $RUNDIR
+    echo -n "Starting $DESC: "
+    mkdir -p $RUNDIR
+    touch $PIDFILE
+    chown redis:redis $RUNDIR $PIDFILE
+    chmod 755 $RUNDIR
 
-	if [ -n "$ULIMIT" ]
-	then
-		ulimit -n $ULIMIT
-	fi
+    if [ -n "$ULIMIT" ]
+    then
+      ulimit -n $ULIMIT
+    fi
 
-	if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS
-	then
-		echo "$NAME."
-	else
-		echo "failed"
-	fi
-	;;
+    if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS
+    then
+      echo "$NAME."
+    else
+      echo "failed"
+    fi
+    ;;
   stop)
-	echo -n "Stopping $DESC: "
-	if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
-	then
-		echo "$NAME."
-	else
-		echo "failed"
-	fi
-	rm -f $PIDFILE
-	sleep 1
-	;;
+    echo -n "Stopping $DESC: "
+    if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+    then
+      echo "$NAME."
+    else
+      echo "failed"
+    fi
+    rm -f $PIDFILE
+    sleep 1
+    ;;
 
   restart|force-reload)
-	${0} stop
-	${0} start
-	;;
+    ${0} stop
+    ${0} start
+    ;;
 
   status)
-	echo -n "$DESC is "
-	if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
-	then
-		echo "running"
-	else
-		echo "not running"
-		exit 1
-	fi
-	;;
+    echo -n "$DESC is "
+    if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
+    then
+      echo "running"
+    else
+      echo "not running"
+      exit 1
+    fi
+    ;;
 
   *)
-	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
-	exit 1
-	;;
+    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
+    exit 1
+    ;;
 esac
 
 exit 0
